services:
  # Backend Flask uniquement
  - type: web
    name: bleu-reflet-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --chdir backend wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
